name: Compile Allegro 4 Project

on:
  push:
    branches: [ feature/allegro-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc
          sudo apt-get install bison flex curl gcc g++ make texinfo zlib1g-dev g++ unzip
      
      - name: install djgpp
        run: |
          git clone https://github.com/andrewwutw/build-djgpp.git
          cd build-djgpp
          ./build-djgpp.sh 12.2.0

      - name: Clone Allegro 4
        run: |
          git clone https://github.com/msikma/allegro-4.2.2-xc.git
          cd allegro-4.2.2-xc

      - name: Compile Allegro 4
        run: |
          cd allegro-4.2.2-xc
          ./xmake.sh lib

      - name: Compile your project
        run: |
          # Aquí van los comandos para compilar tu proyecto que utiliza Allegro 4
          cd vendor
          ln -s ../allegro-4.2.2-xc allegro-4.2.2-xc
          cd ..
          make clean && make
